#region MASTER KEY
MASTER_KEY = '1234'
#endregion

# KONSTANTE

TITLE_PADX = 5
TITLE_PADY = (20,10)
TITLE_FONT = ('Verdana', 18)

SUBTITLE_PADX = 5
SUBTITLE_PADY = (20,10)
SUBTITLE_FONT = ('Verdana', 14)

BODY_PADX = 10
BODY_PADY = (5,5)
BODY_FONT = ('Verdana', 12)

BTN_PADX = (5,5)
BTN_PADY = 10
BTN_IPADX = 10
BTN_IPADY = 10
BTN_FONT = ('Verdana', 12)

BTN_NUM_PADX = 2
BTN_NUM_PADY = 2

#region BELL RING
BELL_RING = 'RING!!!RING!!!RING!!!\U0001F514\U0001F514\U0001F514'
#endregion

#region COLORS
NAVY = 'navy'
DARK_GREY = 'dark grey'
WHITE = 'white'
#endregion

X = 30
NAME = 'ALGEBRA'

